### ISSUE TITLE
Installation issue: NVHPC does not provide usable BLAS/Lapack for packages

### ISSUE THREAD

**Issue by kwryankrattiger** [spack/spack#32164]
### Steps to reproduce the issue

```console
$ spack install <blas/lapack package> ^nvhpc
```

### Error message

* Plasma 
<details><summary>Error message</summary><pre>
1 error found in build log:
     17    -- Could NOT find MKL (missing: MKL_INCLUDE_DIRS MKL_LIBRARIES)
     18    -- Could NOT find OpenBLAS (missing: OpenBLAS_INCLUDE_DIRS OpenBLAS_LIBRARIES)
     19    -- Could NOT find NetlibCblas (missing: NetlibCblas_INCLUDE_DIRS NetlibCblas_LIBRARIES)
     20    -- Looking for cblas_cgemm
     21    -- Looking for cblas_cgemm - not found
     22    -- Could NOT find Accelerate (missing: Accelerate_INCLUDE_DIRS Accelerate_LIBRARIES)
  >> 23    CMake Error at /home/local/KHQ/ryan.krattiger/repos/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.4.0/cmake-3.22.2-wlku4n7muves6d4xkv2vi3wfwxf32mol/share/cmake-3.22/Modules/FindPackageHandleStandardAr
           gs.cmake:230 (message):
     24      Could NOT find CBLAS (missing: CBLAS_INCLUDE_DIRS CBLAS_LIBRARIES)
     25    Call Stack (most recent call first):
     26      /home/local/KHQ/ryan.krattiger/repos/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.4.0/cmake-3.22.2-wlku4n7muves6d4xkv2vi3wfwxf32mol/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 
           (_FPHSA_FAILURE_MESSAGE)
     27      Modules/FindCBLAS.cmake:69 (find_package_handle_standard_args)
     28      CMakeLists.txt:74 (find_package)
     29    
</pre></details>

* Phist 
<details><summary>Error message</summary><pre>
/home/local/KHQ/ryan.krattiger/repos/spack/var/spack/repos/builtin/packages/phist/package.py:235, in cmake_args:
        232        lapacke_libs = (
        233            spec["lapack:c"].libs + spec["blas:c"].libs + find_system_libraries(["libm"])
        234        ).joined(";")
  >>    235        lapacke_include_dir = spec["lapack:c"].headers.directories[0]
        236
        237        args = [
        238            "-DPHIST_USE_CCACHE=OFF",

</pre></details>

### Information on your system

* **Spack:** 0.19.0.dev0 (f0321343a2536acc573e6dea9fd0c7193737d134)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-zen2
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt.plasma-nvhpc.txt](https://github.com/spack/spack/files/9339615/spack-build-env.txt.plasma-nvhpc.txt)
[spack-build-out.txt.plasma-nvhpc.txt](https://github.com/spack/spack/files/9339616/spack-build-out.txt.plasma-nvhpc.txt)

Inspecting the package, this issue is the result of nvhpc depending on `makelocalrc` having been run and configuring the includes. The other half of the issue is nvhpc does not expose `headers` correctly (#32145) causing some `package.py` to fail to configure packages.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by kwryankrattiger** [comment]
There are also issues when using nvhpc with openmp because it puts the nvhpc libgomp.so in the path but that library is not usable when the nvhpc environment is not configured correctly.

Ref. butterfly
<details><summary>Error message</summary><pre>
  >> 2058    /usr/bin/ld: CMakeFiles/ie3d.dir/EMSURF_Driver.f90.o: undefined re
             ference to symbol 'omp_get_wtime_@@@@VERSION'
  >> 2059    /usr/bin/ld: /home/software/spack/__spack_path_placeholder__/__spa
             ck_path_placeholder__/__spack_path_placeholder__/__spack_path_plac
             eholder__/__spack_path_placeholder__/__spack_path_placeholder__/__
             spack_path_placeholder__/__spack_path_placeholder__/__spack_path_p
             laceholder__/__spack_path_placeholder__/__spack_path_placeholder__
             /__spack_path_placeholder__/__spack_path_placeholder__/__spack_pat
             h_placeholder__/__spack_path_placeholder__/__spack_path_placeholde
             r__/__spack_path_placeholder__/__spack_path_placeholder__/__spa/li
             nux-ubuntu22.04-x86_64/gcc-11.2.0/nvhpc-22.7-zoqm7b6df3gao7k23vosl
             unitvvibrjh/Linux_x86_64/22.7/compilers/lib/libnvomp.so: error add
             ing symbols: DSO missing from command line
</pre></details>

**Comment by jthies** [comment]
related PR: #33132 (targets openblas but may help to support nvhpc lapack in phist, too)

**Comment by giordano** [comment]
I ran into this issue as well.  After one installs nvhpc with `spack` and adds it as compiler, a simple reproducer is

```
$ spack python
>>> spec = spack.spec.Spec("py-numpy %nvhpc").concretized()
>>> spec['blas'].headers
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lustre/scratch/scratch/cceamgi/repo/hpc-spack-0.21/mg-initial-stack/spack/lib/spack/spack/spec.py", line 1223, in __get__
    value = f()
  File "/lustre/scratch/scratch/cceamgi/repo/hpc-spack-0.21/mg-initial-stack/spack/lib/spack/spack/spec.py", line 1215, in <lambda>
    callbacks_chain.append(lambda: self.default(self, instance, cls))
  File "/lustre/scratch/scratch/cceamgi/repo/hpc-spack-0.21/mg-initial-stack/spack/lib/spack/spack/spec.py", line 1102, in _headers_default_handler
    raise spack.error.NoHeadersError(msg.format(spec.name, home))
spack.error.NoHeadersError: Unable to locate nvhpc headers in /lustre/scratch/scratch/cceamgi/repo/hpc-spack-0.21/mg-initial-stack/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_placeholder__/__spack_p/linux-rhel7-skylake_avx512/gcc-11.2.1/nvhpc-23.9-mzxkpa2tnhlvi5dbcs3pb6eacrgpfmq5
```

@haampie suggested that the `nvhpc` package is missing a `headers` property to make the header files available.  Note also that `nvhpc` _**defaults**_ to providing BLAS
https://github.com/spack/spack/blob/e30fedab102f9281a220fb4fae82e3f8c43a82ac/var/spack/repos/builtin/packages/nvhpc/package.py#L361
but it can't use it, I don't know how anyone is able to build anything with this toolchain.  This issue, together with #42879 (somewhat related, also about compiler not finding its own files), makes it very hard to `nvhpc` for any non-trivial packages.

For the record, my spack configuration is
* **Spack:** 0.21.1 (e30fedab102f9281a220fb4fae82e3f8c43a82ac)
* **Python:** 3.6.8
* **Platform:** linux-rhel7-skylake_avx512
* **Concretizer:** clingo

**Comment by mirenradia** [comment]
I just ran into this problem with spack 0.22.2 (594a376c521cc746978571b1181a47bbcff30a21) when trying to install `py-numpy` (as a dependency for `paraview`) with `nvhpc@24.3 +blas` in the environment.

I'm confused by https://github.com/spack/spack/issues/32145#issuecomment-2040475650. Is this issue supposed to have been resolved?

**Comment by giordano** [comment]
I don't see the `headers` property being set in https://github.com/spack/spack/blob/cbdc07248f517e5d8f8e56f5e59359794bda6757/var/spack/repos/builtin/packages/nvhpc/package.py so I'm not sure this issue was really solved (I never addressed it myself because I simply gave up using `nvhpc`)

**Comment by basava70** [comment]
I have the same problem with Spack 0.22.1 while installing py-numpy@1.24.3 with nvhpc@24.3 +blas.
It says unable to locate headers ... 
blas_headers = spec["blas"].headers

**Comment by JGaed** [comment]
The problem still seems to exist. When trying to install `py-numpy` (as a dependency of `py-torch`), it cannot find the `blas` header from `nvhpc`. 

```
==> Installing py-numpy-2.3.1-3ymraqodykfqee3xuiweot6mvcwsp6yz [88/89]
==> Fetching https://files.pythonhosted.org/packages/source/n/numpy/numpy-2.3.1.tar.gz
    [100%]   20.39 MB @   92.1 MB/s
==> Applied patch /home/ipeadmin/.spack/package_repos/fncqgg4/repos/spack_repo/builtin/packages/py_numpy/check_executables.patch
==> py-numpy: Executing phase: 'install'
==> Error: NoHeadersError: Unable to locate nvhpc headers in /share/apps/sw-tree/skylake_gpu/linux-skylake_avx512/nvhpc-25.5-qqsyxk6h65yzab737woh6gahjlz2fw5t

/home/ipeadmin/.spack/package_repos/fncqgg4/repos/spack_repo/builtin/packages/py_numpy/package.py:422, in blas_lapack_site_cfg:
        419                f.write("rpath = {0}\n".format(dirs))
        420
        421        blas_libs = spec["blas"].libs
  >>    422        blas_headers = spec["blas"].headers
        423
        424        lapack_libs = spec["lapack"].libs
        425        lapack_headers = spec["lapack"].headers

```

`spack version: "1.1.0.dev0 (2392f747559d3a69f795882728af4af4a8d8e795)"`

```
[+]  nvhpc@25.5+blas+lapack~mpi build_system=generic default_cuda=default install_type=single arch=linux-almalinux9-skylake_avx512 
[e]      ^gcc@11.5.0~binutils+bootstrap~graphite~nvptx~piclibs~profiled~strip build_system=autotools build_type=RelWithDebInfo languages:='c,c++,d,fortran' arch=linux-almalinux9-skylake_avx512
```
