### ISSUE TITLE
pkg-config fails to build on macOS

### ISSUE THREAD

**Issue by deOliveira-R** [spack/spack#4519]
Hi,

I was trying to compile some programs (libgd and parmgridgen) and at some point in their installation, they both require pkg-config-0.29.2.

My problem is, pkg-config fails to build (the log file is attached).

Can anyone reproduce this issue and does it have a known solution?
My system is running macOS Sierra.

[spack-build.txt](https://github.com/LLNL/spack/files/1078537/spack-build.txt)

**Comment by mathstuf** [comment]
My guess is that pkg-config is setting `-Werror` on something and then choking on something in system headers.

**Comment by naromero77** [comment]
I do not even get that far. I get a failure in configure.

**Comment by mathstuf** [comment]
The log in the description shows that it gets to the build.

**Comment by adamjstewart** [comment]
I was able to reproduce this bug on macOS Sierra with GCC 6.3.0. It builds fine with Apple clang though. I would suggest contacting the developers.

**Comment by eschnett** [comment]
I confirm that the solution is to build with Apple's Clang instead of GCC. There are a number of packages that have such issues. In other words, you need to pass a respective `^pkgconfig %clang`. You might also need to explicitly specify other intermediate dependencies and/or variants, even if they are the default.

To ensure that your other packages are not built with Clang, you'll also need to explicitly specify `%gcc` at (possibly several) other locations. This is well within the capabilities of Spack, but the resulting command line is very lengthy.

In fact, I usually create a new package that doesn't install anything, but only depends on other packages so that I don't have to re-type these dependency chains.

These issues are well known for Spack, and are described (with their work-arounds) in various open issues.

@adamjstewart Contacting the `pkgconfig` developers is a nice idea in principle, but the main motivation for using Spack is just that one can build packages without having to resolve many issues with upstream -- instead, Spack can contain patches and configuration options to make things "just work". Unfortunately, that doesn't yet extend to using different compilers, though. I'm hoping that the current work on build dependencies will improve the situation.

**Comment by adamjstewart** [comment]
> the main motivation for using Spack is just that one can build packages without having to resolve many issues with upstream

If something doesn't build, it doesn't build. That's not Spack's fault, and I don't recall anywhere that we claim to magically make things just work 😆 

> instead, Spack can contain patches and configuration options to make things "just work". 

Yes, and these patches often come from upstream. If you want to spend hours digging through the source code to fix a bug, then be my guest, but you should probably contribute it back to upstream anyway. In my experience, developers are happy to help when it comes to compiler support, and if you ask them nicely, they will solve all of your problems. I've added patches from developers to fix dozens of packages that couldn't be compiled with PGI, and now every future release contains those patches. 

Using free open source software comes with its obligations. If you're a good person, you will report bugs so that other people don't run into them. This is just as important for compiler bugs as it is for run-time bugs. The developers don't want potential users thinking "wow, this is so buggy, I can't even compile it" anymore than you want to not be able to compile it.

Anyway, @eschnett's solution is perfectly valid. Until someone reports the bug to the developers and the developers fix the problem/contribute a patch, you'll have to use:
```
$ spack install parmgridgen %gcc +mpi ^openmpi ^pkgconfig %clang
$ spack install libgd %gcc ^pkg-config %clang
```

**Comment by mathstuf** [comment]
+100 to @adamjstewart. Please submit patches upstream that Spack adds to packages. Unless they are 100% known to be Spack-specific, I'd even ask that issues be opened for each patch Spack ships to help track its way to the proper upstream repository (sometimes upstream says "no, that's not how it's supposed to work; here's a proper fix").

As a maintainer of FOSS projects, there's not much worse than hearing about a problem that was fixed in some distribution two years ago, but they never said anything about it. There's also the bugs created by these patches that are really hard to track down when reports make their way to the maintainers…

**Comment by eschnett** [comment]
I did not (or did not want to) say what @adamjstewart or @mathstuf are reading into my statement regarding me expecting other Spack contributors to create Spack-private patches for packages I need. Or maybe I am now reading too much into their statements... Be that as it may, I'm adding my "+100" to @adamjstewart and @mathstuf as well.

**Comment by alalazo** [comment]
This issue is still there. On my Mac I get:

<details>
<summary>$spack install pig-config %gcc@10.2.0 </summary>

```
==> Installing pkg-config-0.29.2-zvqhhp5ofrpewyy74myogyo6k2ayj6kd
==> No binary for pkg-config-0.29.2-zvqhhp5ofrpewyy74myogyo6k2ayj6kd found: installing from source
==> Fetching https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/_source-cache/archive/6f/6fc69c01688c9458a57eb9a1664c9aba372ccda420a02bf4429fe610e7e7d591.tar.gz
##################################################################################################################################################################################################### 100.0%
==> No patches needed for pkg-config
==> pkg-config: Executing phase: 'autoreconf'
==> pkg-config: Executing phase: 'configure'
checking for sysroot... no
[ ... ]
  CC       libglib_2_0_la-gunicollate.lo
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/AuthSession.h:32,
                 from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/Security.h:42,
                 from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/OSServices.framework/Headers/CSIdentity.h:43,
                 from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/OSServices.framework/Headers/OSServices.h:29,
                 from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Headers/IconsCore.h:23,
                 from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Headers/LaunchServices.h:23,
                 from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:39,
                 from gunicollate.c:30:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/Authorization.h:193:7: error: variably modified 'bytes' at file scope
  193 |  char bytes[kAuthorizationExternalFormLength];
      |       ^~~~~
make[6]: *** [libglib_2_0_la-gunicollate.lo] Error 1
make[5]: *** [all-recursive] Error 1
make[4]: *** [all] Error 2
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
==> Error: ProcessError: Command exited with status 2:
    'make'

8 errors found in build log:
     696                     from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/OSServices.fra
            mework/Headers/CSIdentity.h:43,
     697                     from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/OSServices.fra
            mework/Headers/OSServices.h:29,
     698                     from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices
            .framework/Headers/IconsCore.h:23,
     699                     from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices
            .framework/Headers/LaunchServices.h:23,
     700                     from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:39
            ,
     701                     from gunicollate.c:30:
  >> 702    /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Security.framework/Headers/Authorization.h:193:7: error: variably modi
            fied 'bytes' at file scope
     703      193 |  char bytes[kAuthorizationExternalFormLength];
     704          |       ^~~~~
  >> 705    make[6]: *** [libglib_2_0_la-gunicollate.lo] Error 1
  >> 706    make[5]: *** [all-recursive] Error 1
  >> 707    make[4]: *** [all] Error 2
  >> 708    make[3]: *** [all-recursive] Error 1
  >> 709    make[2]: *** [all] Error 2
  >> 710    make[1]: *** [all-recursive] Error 1
  >> 711    make: *** [all] Error 2
```

</details>

This seems to point to these open bugs:
- https://gcc.gnu.org/bugzilla/show_bug.cgi?id=93082
- https://openradar.appspot.com/radar?id=4952611266494464

**Comment by mathstuf** [comment]
Using [`pkgconf`](https://github.com/pkgconf/pkgconf) might be another plausible solution here.

**Comment by alalazo** [comment]
@mathstuf It actually is. I was just verifying if the reported failure was still there (to check if the issue ought to be closed or not).

**Comment by becker33** [comment]
This issue was resolved sometime in the past 3 years.

```
$ spack install pkg-config
[+] /Users/becker33/old_spack_opt/darwin-sonoma-m1/apple-clang-15.0.0.foo/gmake-4.4.1-bdqbn6mzlncn7jfkzqw3urmos4z3qi3m
[+] /Users/becker33/old_spack_opt/darwin-sonoma-m1/apple-clang-15.0.0/gnuconfig-2022-09-17-7gytrfuudfw2tpponhl5i4x4xtmbb6wc
==> Installing pkg-config-0.29.2-sod3ewvq5rezjzsrclzcva7o6jb4tzy5 [3/3]
==> No binary for pkg-config-0.29.2-sod3ewvq5rezjzsrclzcva7o6jb4tzy5 found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/6f/6fc69c01688c9458a57eb9a1664c9aba372ccda420a02bf4429fe610e7e7d591.tar.gz
#########################################################################################################100.0%
==> No patches needed for pkg-config
==> pkg-config: Executing phase: 'autoreconf'
==> pkg-config: Executing phase: 'configure'
==> pkg-config: Executing phase: 'build'
==> pkg-config: Executing phase: 'install'
==> pkg-config: Successfully installed pkg-config-0.29.2-sod3ewvq5rezjzsrclzcva7o6jb4tzy5
  Stage: 0.59s.  Autoreconf: 0.72s.  Configure: 54.15s.  Build: 16.45s.  Install: 0.94s.  Post-install: 0.06s.  Total: 1m 12.97s
[+] /Users/becker33/old_spack_opt/darwin-sequoia-m1/apple-clang-16.0.0/pkg-config-0.29.2-sod3ewvq5rezjzsrclzcva7o6jb4tzy5
```
